version: "3.8"

services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=stakefish
    ports:
      - 3306:3306
  app:
    depends_on:
      - mysql
    build: .
    restart: unless-stopped
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
