apiVersion: v1
kind: Service
metadata:
  name: {{ include "api-deploy.fullname" . }}
  labels:
    {{- include "api-deploy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - nodePort: {{ .Values.service.exposePort }}
      port: {{ .Values.service.internalPort }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "api-deploy.selectorLabels" . | nindent 4 }}
